### ISSUE TITLE
Add upstream matchers

### ISSUE THREAD

**Issue by SimenB** [mrazauskas/tsd-lite#126]
https://github.com/SamVerschueren/tsd/releases/tag/v0.24.0

`expectNever` and `expectDocCommentIncludes` I guess?

**Comment by SimenB** [comment]
@mrazauskas in case you missed this 😀

**Comment by mrazauskas** [comment]
Thanks for reminder. I just wrote a longest essay explaining why I am sceptical about these APIs, but managed to close browser window by accident. All is gone. That’s for good ;D Here is a short version:

- [`eslint-plugin-jsdoc`](https://www.npmjs.com/package/eslint-plugin-jsdoc) looks like way better choice instead of `expectDocCommentIncludes`. I don’t see testing here, it is pure linting.
- motivation behind `expectNever` was to have a replacement for [`assert-never`](https://www.npmjs.com/package/assert-never). That is a one-liner which is meant to be shipped with production code. To me this sounds plain wrong (;

Of course, these judgements are only related with `tsd-lite`.

---

In general, I think that it would be nice to have shorthand matchers for primitive types like: `expectNever`, `expectNumber`, `expectString`, etc. That also means spending some time writing extra docs. Happy to land a PR.

Currently I try to focus on the work-in-progress type testing library. It has these matchers already since early spring. Reworking parser at the moment. The more I can focus on this, the sooner it will be shipped to the world ;D

**Comment by SimenB** [comment]
Fair enough! 👍 

`expectNever` seems kinda useful (to ensure you're exhaustive), although I have no immediate use cases.

**Comment by mrazauskas** [comment]
Sure. If there is a use case, I am more than happy to rethink. Ah.. Probably I should add a note to the readme. Will do.

Closing for now (;

**Comment by mrazauskas** [comment]
For a moment I though this could be a use case for `expectNever` (takes from Jest’s [type tests](https://github.com/facebook/jest/blob/e703e6ed1861595d56e25a764642da5a32b32c5a/packages/jest-mock/__typetests__/mock-functions.test.ts#L124-L137)):

```ts
expectType<'incomplete' | 'return' | 'throw'>(returnValue.type);
expectType<unknown>(returnValue.value);

if (returnValue.type === 'incomplete') {
  expectType<undefined>(returnValue.value);
}

if (returnValue.type === 'return') {
  expectType<boolean>(returnValue.value);
}

if (returnValue.type === 'throw') {
  expectType<unknown>(returnValue.value);
}

// final check to be sure that all members of the union are covered
expectNever(returnValue.type);
```

The test will fail, because the type is still `'incomplete' | 'throw' | 'return'`. To make this work one has to `return` from `if` blocks, but then all has to be wrapped in a function:

```ts
const check = (returnValue: ReturnValue) => {
  expectType<unknown>(returnValue.value);

  if (returnValue.type === 'incomplete') {
    expectType<undefined>(returnValue.value);
    return;
  }

  if (returnValue.type === 'return') {
    expectType<boolean>(returnValue.value);
    return;
  }

  if (returnValue.type === 'throw') {
    expectType<unknown>(returnValue.value);
    return;
  }

  expectNever(returnValue);
};
```

For my eye previous snipped is easier to read. Also its first line ensure exhaustive check.

**Comment by SimenB** [comment]
what about

```ts
if (returnValue.type === 'incomplete') {
  expectType<undefined>(returnValue.value);
} else if (returnValue.type === 'return') {
  expectType<boolean>(returnValue.value);
} else if (returnValue.type === 'throw') {
  expectType<unknown>(returnValue.value);
} else {
  // final check to be sure that all members of the union are covered
  expectNever(returnValue.type);
}
```

?

**Comment by mrazauskas** [comment]
Yep. This works. I though about it after posting ;D
